### ISSUE TITLE
Driver not applied to WS100+

### ISSUE THREAD

**Issue by RandomEngy** [ryanjmulder/smartthings-edge-drivers#10]
Whenever I add a WS100+, it comes back with the legacy Groovy DTH. The WD100+ works fine and picks up this Edge driver.

**Comment by jshessen** [comment]
@RandomEngy -- I know that this is resolved for you, but adding the below as a reference for other users:

Please use the following Repo/Channel moving forward:
https://github.com/jshessen/SmartThingsEdgeDrivers/blob/main/README.md
https://bestow-regional.api.smartthings.com/invite/Kr2z1gQn3ZMA
