### ISSUE TITLE
Had to remove switches to use driver (not an issue)

### ISSUE THREAD

**Issue by dmurchie** [ryanjmulder/smartthings-edge-drivers#2]
Not really an issue - just sharing my experience:

In order to get SmartThings to apply this driver to my HS switches, I had to remove and re-add each switch. FWIW, I added each as "Generic Z-Wave Device" and ST seemed to find the correct driver (based on fingerprint, I suppose).

Really really awesome work!! Thank you!

**Comment by ryanjmulder** [comment]
You're welcome!
