### ISSUE TITLE
WX-300 support

### ISSUE THREAD

**Issue by paulschreiber** [ryanjmulder/smartthings-edge-drivers#3]
Please add support for the [WX-300](https://shop.homeseer.com/products/z-wave-dimmer-switch?variant=40498074189999).

**Comment by ryanjmulder** [comment]
Any idea what the fingerprint is?

**Comment by paulschreiber** [comment]
How do I look that up?

**Comment by paulschreiber** [comment]
HomeSee has [groovy code](https://docs.homeseer.com/products/lighting/hs-wx300/how-to-add-hs-wx300+-to-smartthings-hub)

Looks like the WX300 can have two IDs, depending on if it is in switch or dimmer mode
```groovy
// zw:Ls2a type:1100 mfr:000C prod:4447 model:4036 ver:1.11 zwv:7.15 lib:03 cc:5E,55,9F,6C sec:26,70,5B,85,59,5A,7A,87,72,8E,73,86
fingerprint mfr: "000C", prod: "4447", model: "4036", deviceJoinName: "HomeSeer Wall Dimmer WX300" //WX300 in Dimmer Mode
         
// zw:Ls2a type:1000 mfr:000C prod:4447 model:4037 ver:1.11 zwv:7.15 lib:03 cc:5E,55,9F,6C sec:25,70,5B,85,59,5A,7A,87,72,8E,73,86
fingerprint mfr: "000C", prod: "4447", model: "4037", deviceJoinName: "HomeSeer Wall Switch WX300" //WX300 in Switch Mode
```

Not sure how to handle two virtual devices for one physical device. I made a wx300 and wx300s:
https://github.com/paulschreiber/smartthings-edge-drivers/commit/41b45228d481916e2d3174c3dc68b9881843b6b0

**Comment by ryanjmulder** [comment]
Based on the [user guide](https://docs.homeseer.com/products/lighting/hs-wx300/hs-wx300-user-guide), you have to change the mode before z-wave inclusion, so as far as the hub is concerned the dimmer/switch modes might as well be two different switches entirely.
So, I think your code is correct.
Could you send me a pull request so I can easily merge your changes in?

**Comment by ryanjmulder** [comment]
Thanks, Paul!
